project:
  type: website
  output-dir: docs

website:
  title: "Dr. Yulia Khalikova"
  navbar:
    left:
      - text: "about me"
        href: index.qmd
      - text: "research"
        href: research.qmd
      - text: 'teaching'
        href: teaching.qmd

        

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

editor: visual

