---
title: ""
format: html
---

### Publications
- Voice, Withdrawal, and Judicial Disagreement under Authoritarianism: Evidence from the Russian Constitutional Court. 2026 (Forthcoming). *Politics*

-  Should I Stay, or Should I Go? Self-legitimacy of Attorneys in an Authoritarian State. 2020. *Crime, Law and Social Change*, 75: 373–395. [PDF](https://link.springer.com/article/10.1007/s10611-020-09930-1) (with Anton Kazun)

-  Constitutional Review and Dissenting Opinions in Nondemocracies: An Empirical Analysis of the Russian Constitutional Court, 1998–2018. 2020. *Ekonomicheskaya Sotsiologiya*, 21(3) (2020): 129–150. [PDF](https://jsps.hse.ru/index.php/ecsoc/article/view/10871)\
    *Best Paper Award in Empirical Legal Studies (2nd place), Institute for the Rule of Law, European University at Saint-Petersburg*

------------------------------------------------------------------------

### Working Papers

-   How Authoritarian Courts Use International Law: Evidence from Russia. *Under review*\
    *2021 Best Paper Award for Junior Researchers, Law & Courts Standing Group, ECPR*

-   Authoritarian Control or Legitimacy? Timing Control and Electoral Disputes. *Under review*

-   Constitutional Judicial-Making under Authoritarianism: Empirical Evidence from Russia, 1992–2022. *Preparation for submission*

-   Authoritarian Durability, Prospects of Change and Individual Behavior: Evidence from a Survey Experiment in Russia (with Michael Rochlitz, Olga Masyutina, & Koen Schoors). *Working Papers of Faculty of Economics and Business Administration, Ghent University*, 2023. [PDF](https://econpapers.repec.org/paper/rugrugwps/23_2f1061.htm)

------------------------------------------------------------------------

### Work in Progress

-   Ethnic Bias in Russian Courts\
    (with Dmitrii Shchetinin, Anton Kazun, Nikita Zakharov, Vadim Devyatnikov, and Mikhail Belov) — *First draft*

-   Does Collective Action Depend on Shared Ethnicity? The Case of Domestic Violence Trials in Kazakhstan\
    (with Valeria Umanets and Marcy Shieh) — *First draft*

-   Benefits of Loyal Judiciary: Evidence from District Court Judges — *Data collection*

------------------------------------------------------------------------

### Other Writing

-   “Russia’s Censored Judges.” *Riddle*, December 4, 2021. [URL](https://www.ridl.io/en/russia-s-censored-judges/)
-   “30 Years of Constitutional Justice in the Russian Federation: What Needs to Change?” *Riddle*, August 24, 2021. [URL](https://www.ridl.io/en/30-years-of-constitutional-justice-in-the-russian-federation/)
-   “Russia’s Cat and Mouse Game with International Courts.” *Riddle*, April 8, 2020. [URL](https://www.ridl.io/en/russia-s-cat-and-mouse-game-with-international-courts/)
-   Book Review: *The Political Foundations of Judicial Independence in Dictatorship and Democracy. Democratization*, 28(4) (2020): 859–861. [PDF](https://www.tandfonline.com/doi/epub/10.1080/13510347.2020.1817898)
-   *Eurocast Podcast*, “Russia’s Week”: Episode on the 2020 Russian Constitutional Reform. January 2020. [URL](https://soundcloud.com/eurocast/ep20-russias-week)
